### PR TITLE
Fix KUDO version usage in tests

### LINKED ISSUE #160: Setting DS_KUDO_VERSION externally does not work in tests
Both, `run-pre-checks.sh`, as well as `run-tests.sh` are run as part of our TeamCity CI. There is an option to run custom builds using a specific version of KUDO. This version is injected through the `DS_KUDO_VERSION` env var. Both scripts don't support this variable and will always use a specific version of KUDO (currently 0.15-rc1).

### PR DESCRIPTION
**Pull request by nfnt**
The DS_KUDO_VERSION parameter wasn't honored by 'run-pre-checks.sh' and 'run-tests.sh'. This has been fixed. Most of the functionality of 'kuttl-tests/Makefile' has been extracted into a shell script that uses 'metadata.sh'.
Also removes some redundancies in the scripts.

Fixes #160

### CODE REVIEW

File: tests/run.sh [hunk 1]
```diff
@@ -10,11 +10,8 @@ source "${project_directory}/metadata.sh"
 
 # Note: the following environment variables are required by the shared
 # data-services-kudo tooling.
-export DS_KUDO_VERSION="${DS_KUDO_VERSION:-v${KUDO_VERSION}}"
```
Comment (ANeumann82) [inline tests/run.sh:13]: Why did you remove this one? When this is gone, it basically prevents executing `run.sh` locally, because DS_KUDO_VERSION is undefined.

Comment (nfnt) [reply tests/run.sh:13]: DS_KUDO_VERSION is already set in `metadata.sh`. Setting it here again is redundant.

Comment (ANeumann82) [reply tests/run.sh:13]: Ah 👍

File: kuttl-tests/kind-test.sh [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+KUDO_MACHINE=$(uname -m)
+MACHINE=$(uname -m)
+if [ "${MACHINE}" == "x86_64" ]; then
+  MACHINE=amd64
+fi
+
+mkdir -p bin/
+
+curl -Lo "bin/kubectl_${KUBECTL_VERSION}_${OS}" "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/${OS}/${MACHINE}/kubectl"
```
Comment (zmalik) [inline kuttl-tests/kind-test.sh:27]: this will download on each run. Why not keep them in Makefile targets? and maybe fix them if they were being downloaded on each run

Comment (nfnt) [reply kuttl-tests/kind-test.sh:27]: Makefiles aren't the right tool for the job here. This is more about batching, less about complex dependency management. Furthermore, Makefiles aren't great at handling environment variables and other script related things -- even though it's not impossible. And we already have a defined way of setting up the environment for scripts with `metadata.sh` and should keep using this here.
Good point about the downloads though, let me add some checks for existing binaries.

File: kuttl-tests/kind-test.sh [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+ARTIFACTS=kuttl-dist
+
+OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+KUDO_MACHINE=$(uname -m)
+MACHINE=$(uname -m)
+if [ "${MACHINE}" == "x86_64" ]; then
+  MACHINE=amd64
+fi
+
+mkdir -p bin/
```
Comment (porridge) [inline kuttl-tests/kind-test.sh:25]: Please make the script not silently depend on correct $PWD. Prepend, or worst case - `cd` into `$script_directory`.

File: kuttl-tests/kind-test.sh [hunk 4]
```diff
@@ -0,0 +1,48 @@
+#!/usr/bin/env bash
+
+set -euxo pipefail
```
Comment (porridge) [inline kuttl-tests/kind-test.sh:3]:
```suggestion
set -euo pipefail
```
Do we need the versbosity?

**Review by porridge — APPROVED** [review]

File: kuttl-tests/kind-test.sh (hunk 3 above)
Comment (nfnt) [reply kuttl-tests/kind-test.sh:25]: I agree, but on the other hand that's true for many of the scripts in this project. A correct $PWD is expected. I'd love to clean this up not only here but in the other scripts as well. As part of a separate PR. WDYT?

File: kuttl-tests/kind-test.sh (hunk 4 above)
Comment (nfnt) [reply kuttl-tests/kind-test.sh:3]: For consistency with the existing scripts.

File: kuttl-tests/kind-test.sh (hunk 3 above)
Comment (porridge) [reply kuttl-tests/kind-test.sh:25]: Whatever works for you. Personally I'd improve the script while writing it. Too often I'd find that such future cleanup never actually happens, because there are more important things to do :-)

**Review by ANeumann82 — APPROVED** [review]
